<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCO1d8Xx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCO1d8Xx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCO1d8Xx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCO1d8Xx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCO1d8Xx\App_KernelDevDebugContainer([
    'container.build_hash' => 'CO1d8Xx',
    'container.build_id' => 'f5e9be05',
    'container.build_time' => 1747414950,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCO1d8Xx');
