<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_personne' => [[], ['_controller' => 'App\\Controller\\PersonneController::index'], [], [['text', '/personne']], [], [], []],
    'app_test' => [[], ['_controller' => 'App\\Controller\\PersonneController::test'], [], [['text', '/test']], [], [], []],
    'App\Controller\PersonneController::index' => [[], ['_controller' => 'App\\Controller\\PersonneController::index'], [], [['text', '/personne']], [], [], []],
];
